### PR TITLE
Extensions

### PR DESCRIPTION
**Pull request by MuXodious**
This commit carries over certain excerpts of code that makes arguments working on the Ooba Webui work with the bot, which also allows loading extensions. Not all extensions would be compatible with the bot at this point, if any. You'll have to install individual requirements for the extension you're trying to load.

Edit 1: So far my findings are "google_translate" extension just works™. "EdgeGPT" doesn't work, see the issue. STT won't work, but there are ways to make the bot listen for audio in a voice chat according to Google™. Maybe it's doable?

"silero_tts" works, but the generated sound file isn't send to discord api, and the extension returns a html tag, so bot replies `<audio src="file/extensions/silero_tts/outputs/Diffusion_1652324478.wav" controls autoplay></audio>`.

### CODE REVIEW

**Comment by mercm8** [comment]
Looks like ooba changed a bunch of stuff with the latest update, I'll try your changes after I fix those and then merge - thanks!

**Comment by MuXodious** [comment]
Yeah, I feel like it's the new Chat API behind the breakage. https://github.com/oobabooga/text-generation-webui/commit/c5af549d4b929fec0148704d29af1984ed5d9247

`TypeError: chatbot_wrapper() missing 1 required positional argument: history`

Maybe this project can be done through the API instead of running a skimmed down version of ooba's server.py.

**Comment by mercm8** [comment]
Yeah will probably move to the API once the dust settles.

**Comment by MuXodious** [comment]
Let me know if you need someone for testing. This is likely to turn the bot into a 2 part system like Aiyabot and A111's webui. 

For anyone who wants to keep the bot working, you can checkout to a previous commit in the meantime. I'm keeping my webui at this commit right now: https://github.com/oobabooga/text-generation-webui/commit/1b52bddfcc70d2db88257d36f1c6d182573588c4

`git checkout 1b52bddfcc70d2db88257d36f1c6d182573588c4`

**Pull request merged**
